spring:
  data:
    mongodb:
      uri: mongodb+srv://jaamici:jaamici@jamici.7fe2d.mongodb.net/?retryWrites=true&w=majority&appName=jamici
      database: jamici
      port: 27017
      host: serverlessinstance0.60aj1q0.mongodb.net
  graphql:
    graphiql:
      enabled: true
  mail:
    jndi-name: "mail/Session"
    host: smtp-mail.outlook.com
    port: 587
    username: noreply@jaamici.com
    password: Ugaas123@@@
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
        store:
          protocol: pop3

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: student-service
          # uri: http://localhost:8083
          uri: https://student-service-8a45975e4725.herokuapp.com
          predicates:
            - Path=/api/student-service/graphql, /api/files/**,/api/images/**,/api/student-service/graphql/graphiql
          filters:
           - AuthenticationFilter
           
        - id: university-service
#          uri: https://university-service-a7b11fc7e926.herokuapp.com
          uri: https://university-service-a7b11fc7e926.herokuapp.com
          predicates:
            - Path=/api/university-service/graphql
          filters:
           - AuthenticationFilter
           
        - id: nche-service
          uri: https://nche-service-8eceff6bb0f1.herokuapp.com/
          predicates:
            - Path=/api/nche-service/graphql
          filters:
           - AuthenticationFilter
           
        - id: payment-service
          uri: https://payment-service-app-b2edcbbf6894.herokuapp.com/
          predicates:
            - Path=/api/v1/payment/**
          filters:
           - AuthenticationFilter
           
        - id: identity-service
          # uri: http://localhost:8085
          uri: https://identity-service-12968c326ac9.herokuapp.com
          predicates:
            - Path=/identity/**, /api/tour/**
                       
        - id: slnecb-service
          # uri: http://localhost:8087
          uri: https://slnecb-app-4ba6dee7cde8.herokuapp.com/
          predicates:
            - Path=/api/slnecb/**
          filters:
           - AuthenticationFilter
    config:
      import-check:
        enable: false



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true


graphiql:
  cdn:
    enabled: true

edahab:
  payment:
    apiKey: gMhEEIEVNv3fEHG13zkm7dxow2VARE05EirxzhdJJ
    secretKey: FcGdla9Np0b5bI6Z4npRUEZt7tINfrKoZkIvA5
    agentCode: 725745
    returnUrl: https://www.google.com
jwt:
  secret: ybup2jA94RGV6DbhV5JjvYsaDH3WN3X4OG0mteEyOimzVyB1o0MULDBDFcIvHeiPwZpNXj0xljM14xLPSKAHaE2Ot5KMkWTnbHT5
api:
  key: 58c152d73fff7c85bb2ed325accdb325
  secret: e278484e7cbf649c85cd3dde01f6d73d626a523d0931c7367789e2579af8748e
amount:
  value: 1000
unviversityUrl: https://university.jaamici.com
ncheUrl: https://nche.jaamici.com
